# Generated by Django 5.1.4 on 2024-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.IntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
        ),
    ]
