# Generated by Django 5.1.4 on 2024-12-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='text',
            new_name='example_text',
        ),
    ]
